---
sudo: false
language: ruby
cache: bundler
before_install:
  - bundle -v
install: bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
script:
  - 'bundle exec rake $CHECK'
rvm:
  - '2.3'
  - '2.4'
env:
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
matrix:
  fast_finish: true
  include:
    -
      env: CHECK=rubocop
    -
      env: CHECK="syntax lint"
    -
      env: CHECK=metadata_lint
    -
      env: CHECK=release_checks
    -
      sudo: required
      services: docker
      env: RS_SET="centos-6-docker"
      script: bundle exec rake beaker
    -
      sudo: required
      services: docker
      env: RS_SET="centos-7-docker"
      script: bundle exec rake beaker
    -
      sudo: required
      services: docker
      env: RS_SET="ubuntu-1404-docker"
      script: bundle exec rake beaker
    -
      sudo: required
      services: docker
      env: RS_SET="ubuntu-1604-docker"
      script: bundle exec rake beaker
notifications:
  email: false
